name: Build Notebook LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape
      - name: Upload PDF document
        uses: actions/upload-artifact@v4
        with:
          name: NotebookPDF
          path: main.pdf